# -*- coding: utf-8 -*-
"""“monai-DenseNet121-2-mix.ipynb”

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxpS_6Yg1GCk0y9gzyTlrI4xLHD34gvc

Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

import os

print(os.listdir('/content/drive/MyDrive'))



!pip install -q monai scikit-learn

pip install tqdm

"""
import library
"""

# =========================
# Cell 2: import library
# =========================
# -------------------------------------------------------
import os
import glob
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    classification_report, confusion_matrix,
    roc_auc_score, accuracy_score,
    precision_score, recall_score, f1_score
)
from monai.transforms import (
    Compose, EnsureChannelFirst, EnsureType,
    ScaleIntensity, Resize,
    RandFlip, RandRotate90, RandZoom,
    RandGaussianNoise, RandAdjustContrast
)
from monai.data import ImageDataset, DataLoader
from monai.networks.nets import DenseNet121
from tqdm import tqdm

torch.manual_seed(42)
np.random.seed(42)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

"""Path Configuration

"""

# -------------------------------------------------------
base_dir   = '/content/drive/MyDrive/breast cancer'
train_dir  = os.path.join(base_dir, 'train')
valid_dir  = os.path.join(base_dir, 'valid')
test_dir   = os.path.join(base_dir, 'test')
model_path = '/content/drive/MyDrive/best_densenet121_cbam.pth'

print(os.listdir('/content/drive/MyDrive'))

"""Build a data list

"""

# -------------------------------------------------------
def build_file_list(data_dir):
    image_files, labels = [], []
    for class_name in ['0', '1']:
        class_dir = os.path.join(data_dir, class_name)
        files = glob.glob(os.path.join(class_dir, '*'))
        image_files.extend(files)
        labels.extend([int(class_name)] * len(files))
    return image_files, labels

train_files, train_labels = build_file_list(train_dir)
valid_files, valid_labels = build_file_list(valid_dir)
test_files,  test_labels  = build_file_list(test_dir)

print(f'Train: {len(train_files)} | Valid: {len(valid_files)} | Test: {len(test_files)}')
print(f'Train class 0: {train_labels.count(0)}, class 1: {train_labels.count(1)}')

# =============================================
# DATA VISUALISATION 1: How many images do we have?
# =============================================

splits      = ['Train', 'Valid', 'Test']
class0_counts = [train_labels.count(0), valid_labels.count(0), test_labels.count(0)]
class1_counts = [train_labels.count(1), valid_labels.count(1), test_labels.count(1)]

x = np.arange(len(splits))
width = 0.35

fig, ax = plt.subplots(figsize=(8, 5))
bars1 = ax.bar(x - width/2, class0_counts, width, label='Benign (0)',    color='steelblue')
bars2 = ax.bar(x + width/2, class1_counts, width, label='Malignant (1)', color='tomato')

# add number on top of each bar
for bar in bars1 + bars2:
    ax.text(bar.get_x() + bar.get_width()/2,
            bar.get_height() + 5,
            str(int(bar.get_height())),
            ha='center', fontsize=10, fontweight='bold')

ax.set_xticks(x)
ax.set_xticklabels(splits, fontsize=12)
ax.set_ylabel('Number of Images')
ax.set_title('How Many Images Are in Each Split?')
ax.legend()
plt.tight_layout()
plt.show()

print(f"Total images: Train={len(train_files)}, Valid={len(valid_files)}, Test={len(test_files)}")

# ==============================================
# DATA VIZ 1: Show sample images from each class
# ==============================================
import random
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Diagnostic check
benign_files    = [f for f, l in zip(train_files, train_labels) if l == 0]
malignant_files = [f for f, l in zip(train_files, train_labels) if l == 1]

print(f"Benign samples found:    {len(benign_files)}")
print(f"Malignant samples found: {len(malignant_files)}")
print(f"Total train_files:       {len(train_files)}")
print(f"Unique labels:           {set(train_labels)}")

# Safe sample size
n = min(5, len(benign_files), len(malignant_files))
if n == 0:
    raise RuntimeError("No samples found — check that train_files and train_labels are loaded correctly.")

benign_samples    = random.sample(benign_files, n)
malignant_samples = random.sample(malignant_files, n)

fig, axes = plt.subplots(2, n, figsize=(3 * n, 6))
fig.suptitle('Sample Images: Benign (top) vs Malignant (bottom)', fontsize=14)

for i in range(n):
    img = mpimg.imread(benign_samples[i])
    axes[0, i].imshow(img, cmap='gray')
    axes[0, i].set_title(f'Benign {i+1}', color='steelblue')
    axes[0, i].axis('off')

    img = mpimg.imread(malignant_samples[i])
    axes[1, i].imshow(img, cmap='gray')
    axes[1, i].set_title(f'Malignant {i+1}', color='tomato')
    axes[1, i].axis('off')

plt.tight_layout()
plt.show()

# ==============================================
# DATA VIZ 2: Pixel intensity distribution
# Are benign and malignant images darker or brighter?
# ==============================================
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os # Ensure os is imported here
import glob # Ensure glob is imported here

# --- Start of added code to resolve NameError for train_files ---
# Path Configuration (from 1ZA16Y9LSB0F)
base_dir   = '/content/drive/MyDrive/breast cancer'
train_dir  = os.path.join(base_dir, 'train')
# build_file_list function (from ud75oAgjScj0)
def build_file_list(data_dir):
    image_files, labels = [], []
    for class_name in ['0', '1']:
        class_dir = os.path.join(data_dir, class_name)
        files = glob.glob(os.path.join(class_dir, '*'))
        image_files.extend(files)
        labels.extend([int(class_name)] * len(files))
    return image_files, labels
# Create train_files and train_labels (from ud75oAgjScj0)
train_files, train_labels = build_file_list(train_dir)
# --- End of added code ---


# Get some random files from each class
benign_files    = [f for f, l in zip(train_files, train_labels) if l == 0]
malignant_files = [f for f, l in zip(train_files, train_labels) if l == 1]

benign_pixels    = []
malignant_pixels = []

# Read 100 images from each class and collect all pixel values
for f in benign_files[:20]:
    img = mpimg.imread(f)
    benign_pixels.extend(img.flatten())

for f in malignant_files[:20]:
    img = mpimg.imread(f)
    malignant_pixels.extend(img.flatten())

plt.figure(figsize=(10, 5))
plt.hist(benign_pixels,    bins=50, alpha=0.6, color='steelblue', label='Benign',    density=True)
plt.hist(malignant_pixels, bins=50, alpha=0.6, color='tomato',    label='Malignant', density=True)
plt.xlabel('Pixel Intensity Value')
plt.ylabel('Frequency (normalised)')
plt.title('Pixel Intensity Distribution: Benign vs Malignant')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

print(f"Benign mean intensity:    {np.mean(benign_pixels):.3f}")
print(f"Malignant mean intensity: {np.mean(malignant_pixels):.3f}")

# ==============================================
# DATA VIZ 3: Original image sizes before resizing
# Good to check: are images all the same shape?
# ==============================================
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

heights_b, widths_b = [], []
heights_m, widths_m = [], []

# Loop through 200 images and record their heights and widths
for f in benign_files[:200]:
    img = mpimg.imread(f)
    heights_b.append(img.shape[0])
    widths_b.append(img.shape[1])

for f in malignant_files[:200]:
    img = mpimg.imread(f)
    heights_m.append(img.shape[0])
    widths_m.append(img.shape[1])

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].scatter(widths_b,  heights_b,  alpha=0.4, color='steelblue', label='Benign',    s=10)
axes[0].scatter(widths_m,  heights_m,  alpha=0.4, color='tomato',    label='Malignant', s=10)
axes[0].set_xlabel('Width (px)')
axes[0].set_ylabel('Height (px)')
axes[0].set_title('Image Sizes (width vs height)')
axes[0].legend()

axes[1].hist(heights_b, bins=20, alpha=0.6, color='steelblue', label='Benign')
axes[1].hist(heights_m, bins=20, alpha=0.6, color='tomato',    label='Malignant')
axes[1].set_xlabel('Image Height (px)')
axes[1].set_ylabel('Count')
axes[1].set_title('Height Distribution')
axes[1].legend()

plt.tight_layout()
plt.show()

# =========================
# Data augmentation (addressing class imbalance: applying more augmentation to the minority class)
# -------------------------------------------------------
IMG_SIZE = 96

train_transforms = Compose([
    EnsureChannelFirst(),
    EnsureType(),
    ScaleIntensity(),
    Resize((IMG_SIZE, IMG_SIZE)),
    RandFlip(prob=0.5, spatial_axis=0),
    RandFlip(prob=0.5, spatial_axis=1),
    RandRotate90(prob=0.5),
    RandZoom(prob=0.3, min_zoom=0.85, max_zoom=1.15),
    RandGaussianNoise(prob=0.2, mean=0.0, std=0.05),
    RandAdjustContrast(prob=0.2, gamma=(0.8, 1.2)),
])

val_transforms = Compose([
    EnsureChannelFirst(),
    EnsureType(),
    ScaleIntensity(),
    Resize((IMG_SIZE, IMG_SIZE)),
])

# ==============================================
# DATA VIZ 4: Show what augmentation looks like
# Pick 1 image and apply each transform separately
# ==============================================
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.image as mpimg
import os
import glob
from monai.transforms import (
    Compose, EnsureChannelFirst, EnsureType,
    ScaleIntensity, Resize,
    RandFlip, RandRotate90, RandZoom, RandGaussianNoise
)

# --- Start of added code to ensure variables are populated ---
# Path Configuration (from 1ZA16Y9LSB0F)
base_dir   = '/content/drive/MyDrive/breast cancer'
train_dir  = os.path.join(base_dir, 'train')

print(f"Checking base_dir: {base_dir}")
print(f"base_dir exists: {os.path.exists(base_dir)}")
if os.path.exists(base_dir) and os.path.isdir(base_dir):
    print(f"Contents of base_dir: {os.listdir(base_dir)}")
else:
    print(f"Base directory {base_dir} does not exist or is not a directory.")

print(f"Checking train_dir: {train_dir}")
print(f"train_dir exists: {os.path.exists(train_dir)}")
if os.path.exists(train_dir):
    print(f"Contents of train_dir: {os.listdir(train_dir)}")
    class0_path = os.path.join(train_dir, '0')
    class1_path = os.path.join(train_dir, '1')
    print(f"Contents of class 0 dir: {os.listdir(class0_path) if os.path.exists(class0_path) else 'Does not exist'}")
    print(f"Contents of class 1 dir: {os.listdir(class1_path) if os.path.exists(class1_path) else 'Does not exist'}")
else:
    print("train_dir does not exist, check drive mounting or path.")


# build_file_list function (from ud75oAgjScj0)
def build_file_list(data_dir):
    image_files, labels = [], []
    for class_name in ['0', '1']:
        class_dir = os.path.join(data_dir, class_name)
        # Add print to check individual class_dir
        print(f"Checking class_dir: {class_dir}")
        print(f"class_dir exists: {os.path.exists(class_dir)}")
        if os.path.exists(class_dir):
            files = glob.glob(os.path.join(class_dir, '*'))
            print(f"Found {len(files)} files in {class_dir}")
            if not files: # If no files found, check if directory is empty
                print(f"Directory {class_dir} exists but no files found with pattern '*' (perhaps files are hidden or of different extension?)")
            image_files.extend(files)
            labels.extend([int(class_name)] * len(files))
        else:
            print(f"Class directory {class_dir} does not exist.")
    return image_files, labels

# Create train_files and train_labels (from ud75oAgjScj0)
train_files, train_labels = build_file_list(train_dir)
print(f"After build_file_list: len(train_files)={len(train_files)}, len(train_labels)={len(train_labels)}")

# Get benign and malignant files (from THVgY06RCrpf)
benign_files    = [f for f, l in zip(train_files, train_labels) if l == 0]
malignant_files = [f for f, l in zip(train_files, train_labels) if l == 1]
print(f"len(benign_files)={len(benign_files)}, len(malignant_files)={len(malignant_files)}")

# --- End of added code ---

# Pick one image to experiment on
# Ensure there are benign files before attempting to access
if not benign_files:
    raise RuntimeError("No benign image files found. Check your data directory and file loading.")
sample_file = benign_files[0]

# Base transform just resizes and normalises
base_transform = Compose([EnsureChannelFirst(), EnsureType(), ScaleIntensity(), Resize((96, 96))])

# Apply base first so we always have a clean starting image
base_img = base_transform(sample_file)

# Now define extra transforms that work ON the already-transformed tensor
# We use prob=1.0 to force the transform to always apply
extra_transforms = {
    'Original':          None,
    'Flip horizontal':   RandFlip(prob=1.0, spatial_axis=1),
    'Flip vertical':     RandFlip(prob=1.0, spatial_axis=0),
    'Rotate 90':         RandRotate90(prob=1.0, max_k=1),
    'Add noise':         RandGaussianNoise(prob=1.0, mean=0.0, std=0.15),
    'Zoom in':           RandZoom(prob=1.0, min_zoom=1.2, max_zoom=1.2),
}

fig, axes = plt.subplots(1, 6, figsize=(18, 3))
fig.suptitle('Data Augmentation Examples (same image, different transforms)', fontsize=13)

for ax, (name, transform) in zip(axes, extra_transforms.items()):
    if transform is None:
        img_to_show = base_img[0]   # original — just use base
    else:
        img_to_show = transform(base_img)[0]  # apply extra transform on top

    # clip values so display doesn't break from noise going out of range
    img_to_show = np.clip(img_to_show, 0, 1)
    ax.imshow(img_to_show, cmap='gray')
    ax.set_title(name, fontsize=9)
    ax.axis('off')

plt.tight_layout()
plt.show()

"""DataLoader"""

# =========================
# DataLoader
# -------------------------------------------------------
BATCH_SIZE  = 8
NUM_WORKERS = 2

train_ds = ImageDataset(image_files=train_files, labels=train_labels, transform=train_transforms)
valid_ds = ImageDataset(image_files=valid_files, labels=valid_labels, transform=val_transforms)
test_ds  = ImageDataset(image_files=test_files,  labels=test_labels,  transform=val_transforms)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=NUM_WORKERS)
valid_loader = DataLoader(valid_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)

print(f'Train batches: {len(train_loader)} | Valid batches: {len(valid_loader)}')

"""cbam"""

# =========================
# 6. CBAM
# -------------------------------------------------------

class ChannelAttention(nn.Module):
    """
    Channel Attention Module (SE-like)
    Learn a weight for each channel
    """
    def __init__(self, in_channels, reduction=16):
        super().__init__()
        mid = max(in_channels // reduction, 8)   # 防止太小
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(in_channels, mid, bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(mid, in_channels, bias=False),
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        b, c, _, _ = x.size()
        avg = self.fc(self.avg_pool(x).view(b, c))
        mx  = self.fc(self.max_pool(x).view(b, c))
        attn = self.sigmoid(avg + mx).view(b, c, 1, 1)
        return x * attn


class SpatialAttention(nn.Module):
    """
    Spatial Attention Module

    """
    def __init__(self, kernel_size=7):
        super().__init__()
        padding = kernel_size // 2
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=padding, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg = torch.mean(x, dim=1, keepdim=True)
        mx, _ = torch.max(x, dim=1, keepdim=True)
        attn = self.sigmoid(self.conv(torch.cat([avg, mx], dim=1)))
        return x * attn


class CBAM(nn.Module):
    """
    """
    def __init__(self, in_channels, reduction=16, kernel_size=7):
        super().__init__()
        self.channel_attn  = ChannelAttention(in_channels, reduction)
        self.spatial_attn  = SpatialAttention(kernel_size)

    def forward(self, x):
        x = self.channel_attn(x)
        x = self.spatial_attn(x)
        return x

"""Model Definition (Improved DenseNet)"""

# =========================
# Improved DenseNet121 + CBAM
# -------------------------------------------------------

class DenseNetWithCBAM(nn.Module):
    """
    Insert CBAM after the output of the DenseNet121 feature extractor,
    then connect it to a custom classification head.
    """
    def __init__(self, num_classes=2, dropout_rate=0.4):
        super().__init__()

        # DenseNet121 backbone
        backbone = DenseNet121(spatial_dims=2, in_channels=3, out_channels=1024)
        self.features = backbone.features

        # CBAM
        self.cbam = CBAM(in_channels=1024, reduction=16, kernel_size=7)

        # classifier
        self.classifier = nn.Sequential(
            nn.ReLU(inplace=True),
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Dropout(p=dropout_rate),
            nn.Linear(1024, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(p=dropout_rate / 2),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        feat = self.features(x)   # (B, 1024, H', W')
        feat = self.cbam(feat)    # CBAM attention
        out  = self.classifier(feat)
        return out


model = DenseNetWithCBAM(num_classes=2, dropout_rate=0.4).to(device)
print(model)

"""训练配置

"""

# =========================
# Cell 9: Training Configuration (Incorporating category weights to address class imbalance)
# -------------------------------------------------------
MAX_EPOCHS   = 20
LR           = 1e-4
WEIGHT_DECAY = 1e-4
PATIENCE     = 7

n0 = train_labels.count(0)
n1 = train_labels.count(1)
total = n0 + n1
w0 = total / (2 * n0)
w1 = total / (2 * n1)
class_weights = torch.tensor([w0, w1], dtype=torch.float32).to(device)
print(f'Class weights → 0: {w0:.4f}, 1: {w1:.4f}')

loss_fn   = nn.CrossEntropyLoss(weight=class_weights)
optimizer = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=MAX_EPOCHS, eta_min=1e-6)

"""Training Cycle (Core)"""

#. Training Cycle
# -------------------------------------------------------
train_losses, val_accs, val_losses, lr_history = [], [], [], []
best_val_acc   = 0.0
patience_count = 0

for epoch in range(MAX_EPOCHS):
    # ---------- Training  ----------
    model.train()
    epoch_loss, steps = 0.0, 0
    loop = tqdm(train_loader, desc=f"Epoch [{epoch+1}/{MAX_EPOCHS}]")

    for imgs, labels in loop:
        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(imgs)
        loss    = loss_fn(outputs, labels)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
        steps += 1
        loop.set_postfix(avg_loss=epoch_loss / steps)

    avg_train_loss = epoch_loss / steps
    train_losses.append(avg_train_loss)
    lr_history.append(optimizer.param_groups[0]['lr'])
    scheduler.step()

    # ---------- Validation----------
    model.eval()
    correct, total, val_loss_sum = 0, 0, 0.0

    with torch.no_grad():
        for imgs, labels in valid_loader:
            imgs, labels = imgs.to(device), labels.to(device)
            outputs = model(imgs)
            val_loss_sum += loss_fn(outputs, labels).item()
            preds    = torch.argmax(outputs, dim=1)
            correct += (preds == labels).sum().item()
            total   += len(labels)

    val_acc     = correct / total
    avg_val_loss = val_loss_sum / len(valid_loader)
    val_accs.append(val_acc)
    val_losses.append(avg_val_loss)

    print(
        f"Epoch [{epoch+1:02d}/{MAX_EPOCHS}] "
        f"Train Loss: {avg_train_loss:.4f} | "
        f"Val Loss: {avg_val_loss:.4f} | "
        f"Val Acc: {val_acc:.4f} | "
        f"LR: {lr_history[-1]:.2e}"
    )

    # ---------- Save Best ----------
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), model_path)
        print(f"  ✅ Best model saved (Val Acc: {best_val_acc:.4f})")
        patience_count = 0
    else:
        patience_count += 1

    # ----------Early stop ----------
    if patience_count >= PATIENCE:
        print(f"\n⏹ Early stopping at epoch {epoch+1}")
        break

print(f"\n🏆 Best Validation Accuracy: {best_val_acc:.4f}")

"""Training Visualization"""

#Training Visualization
# -------------------------------------------------------
epochs_ran = len(train_losses)
x = range(1, epochs_ran + 1)

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

axes[0].plot(x, train_losses, marker='o', label='Train Loss')
axes[0].plot(x, val_losses,   marker='s', label='Val Loss')
axes[0].set_title('Loss Curve'); axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss');      axes[0].legend(); axes[0].grid(True)

axes[1].plot(x, val_accs, marker='o', label='Val Accuracy')
axes[1].axhline(y=best_val_acc, linestyle='--', label=f'Best: {best_val_acc:.4f}')
axes[1].set_title('Validation Accuracy'); axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Accuracy');           axes[1].legend(); axes[1].grid(True)

axes[2].plot(x, lr_history, marker='o', label='Learning Rate')
axes[2].set_title('LR Schedule'); axes[2].set_xlabel('Epoch')
axes[2].set_ylabel('LR');         axes[2].legend(); axes[2].grid(True)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/training_curve_cbam.png', dpi=150)
plt.show()

"""Testing and Evaluation"""

#11. Load the best model and evaluate it (on the validation set)
# -------------------------------------------------------
model.load_state_dict(torch.load(model_path, map_location=device))
model.eval()

all_preds  = []
all_labels = []
all_probs  = []   # Probability of Class 1 (for AUC)

with torch.no_grad():
    for imgs, labels in valid_loader:
        imgs    = imgs.to(device)
        outputs = model(imgs)
        probs   = F.softmax(outputs, dim=1)[:, 1]
        preds   = torch.argmax(outputs, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.numpy())
        all_probs.extend(probs.cpu().numpy())

all_preds  = np.array(all_preds)
all_labels = np.array(all_labels)
all_probs  = np.array(all_probs)

"""Confusion matrix"""

#12. Confusion matrix
# -------------------------------------------------------
CLASS_NAMES = ['Benign', 'Malignant']

cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(8, 6))
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
    cbar=True, linewidths=0.5, linecolor='black'
)
plt.xlabel('Predicted Label', fontsize=12)
plt.ylabel('True Label',      fontsize=12)
plt.title('Confusion Matrix (CBAM Model)', fontsize=14)
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/confusion_matrix_cbam.png', dpi=150, bbox_inches='tight')
plt.show()

# ==============================================
# DATA VIZ 5: Training curves (run AFTER training)
# Shows how the model improved (or didn't!) each epoch
# ==============================================
import matplotlib.pyplot as plt

epochs_ran = range(1, len(train_losses) + 1)

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
fig.suptitle('Training Results Over Epochs', fontsize=14)

# Plot 1: Train vs validation loss
axes[0].plot(epochs_ran, train_losses, marker='o', label='Train loss',      color='steelblue')
axes[0].plot(epochs_ran, val_losses,   marker='s', label='Validation loss', color='tomato',    linestyle='--')
axes[0].set_title('Loss (lower is better)')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Plot 2: Validation accuracy
axes[1].plot(epochs_ran, val_accs, marker='o', color='mediumseagreen')
axes[1].axhline(y=best_val_acc, linestyle='--', color='gray', label=f'Best: {best_val_acc:.4f}')
# Mark the best epoch with a star
best_epoch = val_accs.index(max(val_accs)) + 1
axes[1].scatter(best_epoch, max(val_accs), s=200, color='gold', zorder=5, marker='*', label='Best epoch')
axes[1].set_title('Validation Accuracy (higher is better)')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Accuracy')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

# Plot 3: Learning rate schedule
axes[2].plot(epochs_ran, lr_history, marker='o', color='mediumpurple')
axes[2].set_title('Learning Rate Schedule (cosine annealing)')
axes[2].set_xlabel('Epoch')
axes[2].set_ylabel('Learning rate')
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/training_curve_cbam.png', dpi=150)
plt.show()
# ==============================================
# DATA VIZ 6: ROC curve + bar chart of metrics
# Run this AFTER evaluating the model on test set
# ==============================================
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, roc_auc_score, accuracy_score, precision_score, recall_score, f1_score
import numpy as np

# --- ROC curve ---
fpr, tpr, thresholds = roc_curve(all_labels, all_probs)
auc_score = roc_auc_score(all_labels, all_probs)

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

axes[0].plot(fpr, tpr, color='tomato',    linewidth=2, label=f'ROC (AUC = {auc_score:.3f})')
axes[0].plot([0,1], [0,1], color='gray', linestyle='--', label='Random classifier')
axes[0].fill_between(fpr, tpr, alpha=0.1, color='tomato')
axes[0].set_xlabel('False positive rate')
axes[0].set_ylabel('True positive rate')
axes[0].set_title('ROC Curve')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# --- Bar chart of all metrics ---
metric_names  = ['Accuracy', 'Precision', 'Recall', 'F1-score', 'AUC']
metric_values = [
    accuracy_score(all_labels, all_preds),
    precision_score(all_labels, all_preds),
    recall_score(all_labels, all_preds),
    f1_score(all_labels, all_preds),
    auc_score,
]
colors = ['steelblue', 'mediumseagreen', 'tomato', 'mediumpurple', 'orange']

bars = axes[1].bar(metric_names, metric_values, color=colors, edgecolor='white', linewidth=1.2)
axes[1].set_ylim(0, 1.1)
axes[1].axhline(y=0.5, linestyle='--', color='gray', alpha=0.5, label='Baseline (0.5)')
axes[1].set_title('Model Performance Metrics')
axes[1].set_ylabel('Score')
axes[1].legend()

# Add value labels on top of each bar
for bar, val in zip(bars, metric_values):
    axes[1].text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + 0.02,
                 f'{val:.3f}',
                 ha='center', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/roc_and_metrics.png', dpi=150)
plt.show()

#13. Classification Indicators Report
# -------------------------------------------------------
acc       = accuracy_score(all_labels, all_preds)
precision = precision_score(all_labels, all_preds, average='binary')
recall    = recall_score(all_labels, all_preds, average='binary')
f1        = f1_score(all_labels, all_preds, average='binary')

try:
    auc = roc_auc_score(all_labels, all_probs)
except Exception as e:
    auc = None
    print(f"AUC error: {e}")

print("\n===== Overall Classification Metrics (CBAM Model) =====")
print(f"Accuracy : {acc:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-score : {f1:.4f}")
if auc is not None:
    print(f"AUC      : {auc:.4f}")

print("\n===== Classification Report =====")
print(classification_report(
    all_labels, all_preds,
    target_names=CLASS_NAMES, digits=4
))